// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'icon': string;
  'panel-component': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
