// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'attack-container': string;
  'damage': string;
  'name': string;
}
declare var cssExports: CssExports;
export = cssExports;
