// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'detail-container': string;
  'filter-container': string;
  'footer': string;
  'idx-counter': string;
  'item': string;
  'left-panel': string;
  'right-panel': string;
  'search-page': string;
  'separated-list': string;
  'table-header': string;
}
declare var cssExports: CssExports;
export = cssExports;
