// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'attack-container': string;
  'damage': string;
  'detail-container': string;
  'filter-container': string;
  'footer': string;
  'idx-counter': string;
  'image-container': string;
  'information-container': string;
  'item': string;
  'left-panel': string;
  'name': string;
  'pokemon-container': string;
  'pokemon-image': string;
  'pokemon-image-container': string;
  'right-panel': string;
  'search-page': string;
  'text-container': string;
  'title': string;
  'type': string;
}
declare var cssExports: CssExports;
export = cssExports;
