// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'image-container': string;
  'pokemon-image': string;
  'pokemon-image-container': string;
  'text-container': string;
}
declare var cssExports: CssExports;
export = cssExports;
