// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'image-container': string;
  'information-container': string;
  'pokemon-container': string;
  'title': string;
  'type': string;
}
declare var cssExports: CssExports;
export = cssExports;
